language: objective-c
before_install:
- gem i cocoapods --no-ri --no-rdoc
- brew uninstall xctool; brew install xctool --HEAD;
install: pod update
xcode_workspace: SCITokenSearchField.xcworkspace
xcode_scheme: SCITokenSearchField
xcode_sdk: iphonesimulator
